Models/ErrorViewModel.cs
namespace Projem.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Kullanici.cs
namespace Projem.Models;

public class Kullanici
{
    public String? Ad { get; set; } = String.Empty;
    public String? Soyad { get; set; } = String.Empty;
}

Models/KullaniciSifre.cs
namespace Projem.Models;

public class KullaniciSifre
{
    public String? Ad { get; set; } = String.Empty;
    public String? Soyad { get; set; } = String.Empty;
    public String? Sifre { get; set; } = String.Empty;
    public DateTime  KayitTarihi { get; set; }

    public KullaniciSifre()
    {
        KayitTarihi = DateTime.Now;
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Projem.Models;

namespace Projem.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/Neo4jController.cs
using Microsoft.AspNetCore.Mvc;
using Projem.Models;
using Projem.Services;


namespace Projem.Controllers
{
    public class Neo4jController : Controller
    {
        private readonly Neo4jService _neo4jService;

        public Neo4jController(Neo4jService neo4jService)
        {
            _neo4jService = neo4jService;
        }

        public async Task<IActionResult> ShowData()
        {
            var users = await _neo4jService.GetAllNodes();
            return View(users);
        }

        public async Task<IActionResult> ShowDataNode()
        {
            var users = await _neo4jService.GetAllUsers();
            return View(users);
        }
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]//Default(Standart) olarak HttpGet gelir. Burada veri göndereceğimiz anlamına gelir.
        [ValidateAntiForgeryToken] // Güvenlik amaçlı tarayıcıyı doğrular.
        public IActionResult Apply([FromForm] KullaniciSifre model) // Apply fonksiyonu overloading yaptık. 
        {
            _neo4jService.AddNewUser(model);
            return  View("FeedBack",model);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a class="btn btn-outline-success" asp-action="Apply" asp-controller="neo4j">Applications</a>
</div>

Views/Neo4j/Apply.cshtml
@model KullaniciSifre

<div class="display-6">
    Apply
</div>

<form method="post" asp-action="Apply">

    <div class="form-group my-2"> <!-- m = Margin(dış boşluk) y = y ekseni -->
        <label asp-for="Ad"></label>
        <input asp-for="Ad" class="form-control" />
    </div>

    <div class="form-group my-2"> <!-- m = Margin(dış boşluk) y = y ekseni -->
        <label asp-for="Soyad"></label>
        <input asp-for="Soyad" class="form-control" />
    </div>

    <div class="form-group my-2"> <!-- m = Margin(dış boşluk) y = y ekseni -->
        <label asp-for="Sifre"></label>
        <input type="password" asp-for="Sifre" class="form-control" />
    </div>

    <div>
        <button class="btn btn-primary" type="submit">Apply</button>
       
    </div>


</form>

Views/Neo4j/FeedBack.cshtml
@model KullaniciSifre

<div>
    <h3 class="display-4">Congratulations @Model.Ad</h3>
    <p class="lead">Your Application has been <mark>accepted.</mark></p>
    <p class="lead">Many thanks for your interst</p>
    <hr/>
    <blockquote class="blockqoute">
        Your password has been given
    </blockquote>
    <p class="text-muted">You applied at @Model.KayitTarihi </p>
    
    <div class="btn-group">
        <a class="btn btn-outline-success" asp-action="ShowDataNode">Kayıtlar</a>
        <a class="btn btn-success" asp-action="Index" asp-controller="Home">Home</a>
    </div>
</div>

Views/Neo4j/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

Views/Neo4j/ShowData.cshtml
@model List<Projem.Models.Kullanici>

<!DOCTYPE html>
<html>

<head>
    <title>Neo4j Nodes </title>
</head>

<body>
    <h1>Neo4j Nodes  (@Model.Count)</h1>
    <ul>
        <hr>
        @foreach (var nodeName in Model)
        {
            
            <li><b>Ad</b> : @nodeName.Ad</li>
            <li><b>Soyad</b> : @nodeName.Soyad</li>
            <hr>
        }
        <hr>
    </ul>
</body>

</html>

Views/Neo4j/ShowDataNode.cshtml
@model List<Projem.Models.KullaniciSifre>

<!DOCTYPE html>
<html>
<head>
    <title>Users </title>
</head>
<body>
    <h1>Users (@Model.Count)</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Adı</th>
                <th scope="col">Soyadı</th>
                <th scope="col">Şifre</th>
                <th scope="col">Kayıt Tarihi</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.Ad</td>
                    <td>@user.Soyad</td>
                    <td>@user.Sifre</td>
                    <td>@user.KayitTarihi</td>

                </tr>
            }
        </tbody>
    </table>
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Neo4j" asp-action="ShowDataNode">Kayitlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Neo4j" asp-action="ShowData">Kullanıclar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Muhammed Emin YETİM 413553 - Yusuf Buğra ÇELİKER 416582 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>